@isTest
public class apextrigger2testclass {
    
    @isTest
    public static void annhot(){
       /* Account acc = new Account();
        acc.Name='hotcheck';
        acc.AnnualRevenue =null;
        acc.Rating = 'Hot';
        insert acc;*/
        
        Account acc1 = new Account();
        acc1.Name = 'hotColdCheck';
        acc1.Rating = 'Hot';
        acc1.AnnualRevenue = null;
        
        
    }
}