public class demopractice {
    
    public integer b = 20;
    public void details2(integer a){
        
       integer c =a+b;
       system.debug(c);
        
        
    }
    //system.debug(a);
    
   /* public void details(){
        string a;
        string b;
        a = 'prasanth';
        b = 'iam cool';
        system.debug('results:'+a);
	   system.debug('results:'+b);        
                        
    }*/
 
    /*public void details1(string value1,string value2){
        string x;
        string y;
        x = value1;
        y = value2;
        system.debug('results):'+(x+y));        
}*/

}