public class practhot {
    
    public static void htcld(List<Account> at){
   /*    Map<Id,Account> oldRecords = (Map<Id,Account>)Trigger.oldMap;//oldrecords---hot
        for(Account acc:at){//traverse newrecords--cold
         Account oldacc = oldRecords.get(acc.Id);// geting the corresponding values which changes from hot to cold
            if(oldacc.Rating.equals('Hot') && acc.Rating.equals('Cold')
               && acc.AnnualRevenue==null){
                   acc.Active__c='No';
                   
               }
        }*/
       
    }
}