public class workshopday3class {
    
    public void test(){
        integer a;
        integer b;
        integer c;
        integer d;
        integer e;
        integer f;
        
        a = 8;
        b = 4;
        c = a + b;
        d = a - b;
        e = a * b;
        f = a / b;
        system.debug('value of 1st number:'+ a);
        system.debug('value of 2nd number:'+ b);
        system.debug('sum of two number:'+ c);
        system.debug('sub of two number:'+ d);
        system.debug('multiplication of two number:'+e);
        system.debug('division of two number:'+ f);
    }
}