public class workshopday3class2 {
    
    public void sum(){
        integer a;
        integer b ;
        integer c;
        
        a =  8;
        b = 4;
        c = a + b;
        system.debug('value of 1st number:'+ a);
        system.debug('value of 2nd number:'+ b);
        system.debug('sum of the number:'+c);
    }
    
    public void sub(){
        integer a;
        integer b ;
        integer d;
        
        a =  8;
        b = 4;
        d = a - b;
        system.debug('value of 1st number:'+ a);
        system.debug('value of 2nd number:'+ b);
        system.debug('sum of the number:'+d);
    }
     public void multiplication(){
        integer a;
        integer b ;
        integer e;
        
        a =  8;
        b = 4;
        e = a - b;
        system.debug('value of 1st number:'+ a);
        system.debug('value of 2nd number:'+ b);
        system.debug('sum of the number:'+e);
    }
    public void div(){
        integer a;
        integer b ;
        integer f;
        
        a =  8;
        b = 4;
        f = a - b;
        system.debug('value of 1st number:'+ a);
        system.debug('value of 2nd number:'+ b);
        system.debug('sum of the number:'+f);
    }
       
}